### ISSUE TITLE
Drive letter lost

### ISSUE THREAD

**Issue by jonface** [hex7c0/mkdir-recursive#3]
Running under windows, CWD is somewhere on drive X:\.... , mkdirSync() called with a path with another drive as absolute, C:\a\b\c , drive letter 'C' is stripped as 'path.isAbsolute(root)' is true, the path is attempted to be made at X:\a\b\c which is wrong, it should have been C:\a\b\c .

In brief,
CWD = 'X:\d\e\f'
mkdirSync('C:\a\b\c')

Failed as path is changed to 'X:\a\b\c' .

**Comment by hex7c0** [comment]
thanks jonface for the issue
